type LanguageName = { english_name: string; name: string };

export const languages: Record<string, LanguageName> = {
  bi: { english_name: "Bislama", name: "" },
  cs: { english_name: "Czech", name: "Český" },
  ba: { english_name: "Bashkir", name: "" },
  ae: { english_name: "Avestan", name: "" },
  av: { english_name: "Avaric", name: "" },
  de: { english_name: "German", name: "Deutsch" },
  mt: { english_name: "Maltese", name: "Malti" },
  om: { english_name: "Oromo", name: "" },
  rm: { english_name: "Raeto-Romance", name: "" },
  so: { english_name: "Somali", name: "Somali" },
  ts: { english_name: "Tsonga", name: "" },
  vi: { english_name: "Vietnamese", name: "Tiếng Việt" },
  gn: { english_name: "Guarani", name: "" },
  ig: { english_name: "Igbo", name: "" },
  it: { english_name: "Italian", name: "Italiano" },
  ki: { english_name: "Kikuyu", name: "" },
  ku: { english_name: "Kurdish", name: "" },
  la: { english_name: "Latin", name: "Latin" },
  ln: { english_name: "Lingala", name: "" },
  lb: { english_name: "Letzeburgesch", name: "" },
  ny: { english_name: "Chichewa; Nyanja", name: "" },
  pl: { english_name: "Polish", name: "Polski" },
  si: { english_name: "Sinhalese", name: "සිංහල" },
  to: { english_name: "Tonga", name: "" },
  az: { english_name: "Azerbaijani", name: "Azərbaycan" },
  ce: { english_name: "Chechen", name: "" },
  cu: { english_name: "Slavic", name: "" },
  da: { english_name: "Danish", name: "Dansk" },
  hz: { english_name: "Herero", name: "" },
  ie: { english_name: "Interlingue", name: "" },
  rw: { english_name: "Kinyarwanda", name: "Kinyarwanda" },
  mi: { english_name: "Maori", name: "" },
  no: { english_name: "Norwegian", name: "Norsk" },
  pi: { english_name: "Pali", name: "" },
  sk: { english_name: "Slovak", name: "Slovenčina" },
  se: { english_name: "Northern Sami", name: "" },
  sm: { english_name: "Samoan", name: "" },
  uk: { english_name: "Ukrainian", name: "Український" },
  en: { english_name: "English", name: "English" },
  ay: { english_name: "Aymara", name: "" },
  ca: { english_name: "Catalan", name: "Català" },
  eo: { english_name: "Esperanto", name: "Esperanto" },
  ha: { english_name: "Hausa", name: "Hausa" },
  ho: { english_name: "Hiri Motu", name: "" },
  hu: { english_name: "Hungarian", name: "Magyar" },
  io: { english_name: "Ido", name: "" },
  ii: { english_name: "Yi", name: "" },
  kn: { english_name: "Kannada", name: "?????" },
  kv: { english_name: "Komi", name: "" },
  li: { english_name: "Limburgish", name: "" },
  oj: { english_name: "Ojibwa", name: "" },
  ru: { english_name: "Russian", name: "Pусский" },
  sr: { english_name: "Serbian", name: "Srpski" },
  sv: { english_name: "Swedish", name: "svenska" },
  ty: { english_name: "Tahitian", name: "" },
  zu: { english_name: "Zulu", name: "isiZulu" },
  ka: { english_name: "Georgian", name: "ქართული" },
  ch: { english_name: "Chamorro", name: "Finu' Chamorro" },
  be: { english_name: "Belarusian", name: "беларуская мова" },
  br: { english_name: "Breton", name: "" },
  kw: { english_name: "Cornish", name: "" },
  fi: { english_name: "Finnish", name: "suomi" },
  sh: { english_name: "Serbo-Croatian", name: "" },
  nn: { english_name: "Norwegian Nynorsk", name: "" },
  tt: { english_name: "Tatar", name: "" },
  tg: { english_name: "Tajik", name: "" },
  vo: { english_name: "Volapük", name: "" },
  ps: { english_name: "Pushto", name: "پښتو" },
  mk: { english_name: "Macedonian", name: "" },
  fr: { english_name: "French", name: "Français" },
  bm: { english_name: "Bambara", name: "Bamanankan" },
  eu: { english_name: "Basque", name: "euskera" },
  fj: { english_name: "Fijian", name: "" },
  id: { english_name: "Indonesian", name: "Bahasa indonesia" },
  mg: { english_name: "Malagasy", name: "" },
  na: { english_name: "Nauru", name: "" },
  xx: { english_name: "No Language", name: "No Language" },
  qu: { english_name: "Quechua", name: "" },
  sq: { english_name: "Albanian", name: "shqip" },
  ti: { english_name: "Tigrinya", name: "" },
  tw: { english_name: "Twi", name: "" },
  wa: { english_name: "Walloon", name: "" },
  ab: { english_name: "Abkhazian", name: "" },
  bs: { english_name: "Bosnian", name: "Bosanski" },
  af: { english_name: "Afrikaans", name: "Afrikaans" },
  an: { english_name: "Aragonese", name: "" },
  fy: { english_name: "Frisian", name: "" },
  gu: { english_name: "Gujarati", name: "" },
  ik: { english_name: "Inupiaq", name: "" },
  ja: { english_name: "Japanese", name: "日本語" },
  ko: { english_name: "Korean", name: "한국어/조선말" },
  lg: { english_name: "Ganda", name: "" },
  nl: { english_name: "Dutch", name: "Nederlands" },
  os: { english_name: "Ossetian; Ossetic", name: "" },
  el: { english_name: "Greek", name: "ελληνικά" },
  bn: { english_name: "Bengali", name: "বাংলা" },
  cr: { english_name: "Cree", name: "" },
  km: { english_name: "Khmer", name: "" },
  lo: { english_name: "Lao", name: "" },
  nd: { english_name: "Ndebele", name: "" },
  ne: { english_name: "Nepali", name: "" },
  sc: { english_name: "Sardinian", name: "" },
  sw: { english_name: "Swahili", name: "Kiswahili" },
  tl: { english_name: "Tagalog", name: "" },
  ur: { english_name: "Urdu", name: "اردو" },
  ee: { english_name: "Ewe", name: "Èʋegbe" },
  aa: { english_name: "Afar", name: "" },
  co: { english_name: "Corsican", name: "" },
  et: { english_name: "Estonian", name: "Eesti" },
  is: { english_name: "Icelandic", name: "Íslenska" },
  ks: { english_name: "Kashmiri", name: "" },
  kr: { english_name: "Kanuri", name: "" },
  ky: { english_name: "Kirghiz", name: "??????" },
  kj: { english_name: "Kuanyama", name: "" },
  nr: { english_name: "Ndebele", name: "" },
  or: { english_name: "Oriya", name: "" },
  wo: { english_name: "Wolof", name: "Wolof" },
  za: { english_name: "Zhuang", name: "" },
  ar: { english_name: "Arabic", name: "العربية" },
  cv: { english_name: "Chuvash", name: "" },
  fo: { english_name: "Faroese", name: "" },
  hr: { english_name: "Croatian", name: "Hrvatski" },
  ms: { english_name: "Malay", name: "Bahasa melayu" },
  nb: { english_name: "Norwegian Bokmål", name: "Bokmål" },
  rn: { english_name: "Rundi", name: "Kirundi" },
  sn: { english_name: "Shona", name: "" },
  st: { english_name: "Sotho", name: "" },
  tr: { english_name: "Turkish", name: "Türkçe" },
  am: { english_name: "Amharic", name: "" },
  fa: { english_name: "Persian", name: "فارسی" },
  hy: { english_name: "Armenian", name: "" },
  pa: { english_name: "Punjabi", name: "ਪੰਜਾਬੀ" },
  as: { english_name: "Assamese", name: "" },
  ia: { english_name: "Interlingua", name: "" },
  lv: { english_name: "Latvian", name: "Latviešu" },
  lu: { english_name: "Luba-Katanga", name: "" },
  mr: { english_name: "Marathi", name: "" },
  mn: { english_name: "Mongolian", name: "" },
  pt: { english_name: "Portuguese", name: "Português" },
  th: { english_name: "Thai", name: "ภาษาไทย" },
  tk: { english_name: "Turkmen", name: "" },
  ve: { english_name: "Venda", name: "" },
  dv: { english_name: "Divehi", name: "" },
  gv: { english_name: "Manx", name: "" },
  kl: { english_name: "Kalaallisut", name: "" },
  kk: { english_name: "Kazakh", name: "қазақ" },
  lt: { english_name: "Lithuanian", name: "Lietuvių" },
  my: { english_name: "Burmese", name: "" },
  sl: { english_name: "Slovenian", name: "Slovenščina" },
  sd: { english_name: "Sindhi", name: "" },
  cn: { english_name: "Cantonese", name: "广州话 / 廣州話" },
  hi: { english_name: "Hindi", name: "हिन्दी" },
  cy: { english_name: "Welsh", name: "Cymraeg" },
  ht: { english_name: "Haitian; Haitian Creole", name: "" },
  iu: { english_name: "Inuktitut", name: "" },
  jv: { english_name: "Javanese", name: "" },
  mh: { english_name: "Marshall", name: "" },
  sa: { english_name: "Sanskrit", name: "" },
  ss: { english_name: "Swati", name: "" },
  te: { english_name: "Telugu", name: "తెలుగు" },
  kg: { english_name: "Kongo", name: "" },
  ml: { english_name: "Malayalam", name: "" },
  uz: { english_name: "Uzbek", name: "ozbek" },
  sg: { english_name: "Sango", name: "" },
  xh: { english_name: "Xhosa", name: "" },
  es: { english_name: "Spanish", name: "Español" },
  su: { english_name: "Sundanese", name: "" },
  ug: { english_name: "Uighur", name: "" },
  yi: { english_name: "Yiddish", name: "" },
  yo: { english_name: "Yoruba", name: "Èdè Yorùbá" },
  zh: { english_name: "Mandarin", name: "普通话" },
  he: { english_name: "Hebrew", name: "עִבְרִית" },
  bo: { english_name: "Tibetan", name: "" },
  ak: { english_name: "Akan", name: "" },
  mo: { english_name: "Moldavian", name: "" },
  ng: { english_name: "Ndonga", name: "" },
  dz: { english_name: "Dzongkha", name: "" },
  ff: { english_name: "Fulah", name: "Fulfulde" },
  gd: { english_name: "Gaelic", name: "" },
  ga: { english_name: "Irish", name: "Gaeilge" },
  gl: { english_name: "Galician", name: "Galego" },
  nv: { english_name: "Navajo", name: "" },
  oc: { english_name: "Occitan", name: "" },
  ro: { english_name: "Romanian", name: "Română" },
  ta: { english_name: "Tamil", name: "தமிழ்" },
  tn: { english_name: "Tswana", name: "" },
  bg: { english_name: "Bulgarian", name: "български език" },
};
